/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LeftEyebrow.h"
#include "Clock_1.h"
#include "LeftEyebrow1_aliases.h"
#include "LeftEyebrow1.h"
#include "LeftEyebrow2_aliases.h"
#include "LeftEyebrow2.h"
#include "RightEyebrow.h"
#include "Clock_2.h"
#include "RightEyebrow1_aliases.h"
#include "RightEyebrow1.h"
#include "RightEyebrow2_aliases.h"
#include "RightEyebrow2.h"
#include "LeftEyeball.h"
#include "Clock_3.h"
#include "LeftEyeballTop_aliases.h"
#include "LeftEyeballTop.h"
#include "LeftEyeballBottom_aliases.h"
#include "LeftEyeballBottom.h"
#include "RightEyeball.h"
#include "Clock_4.h"
#include "RightEyeballTop_aliases.h"
#include "RightEyeballTop.h"
#include "RightEyeballBottom_aliases.h"
#include "RightEyeballBottom.h"
#include "Eyelids.h"
#include "Clock_5.h"
#include "EyelidTilt_aliases.h"
#include "EyelidTilt.h"
#include "EyelidClose_aliases.h"
#include "EyelidClose.h"
#include "Mouth.h"
#include "Clock_6.h"
#include "TopLip_aliases.h"
#include "TopLip.h"
#include "Jaw_aliases.h"
#include "Jaw.h"
#include "Neck.h"
#include "Clock_7.h"
#include "Left_aliases.h"
#include "Left.h"
#include "Right_aliases.h"
#include "Right.h"
#include "Base.h"
#include "Clock_8.h"
#include "Rotation_aliases.h"
#include "Rotation.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

